# Generated by Django 5.2.1 on 2025-05-13 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('leia_o_livro_url', models.URLField()),
                ('saiba_mais_url', models.URLField()),
                ('galeria_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria_sobre/')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_leitura', models.CharField(choices=[('flipbook', 'Flipbook'), ('pdf', 'PDF')], max_length=10)),
                ('sinopse', models.TextField()),
                ('imagens', models.ImageField(upload_to='imagens_livro/')),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='paginas_livro/')),
                ('numero_pagina', models.IntegerField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='livro3d.livro')),
            ],
            options={
                'ordering': ['numero_pagina'],
            },
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobre_nos', models.TextField()),
                ('sobre_o_livro', models.TextField()),
                ('galeria', models.ManyToManyField(related_name='galerias', to='livro3d.image')),
                ('membros', models.ManyToManyField(to='livro3d.membro')),
            ],
        ),
    ]
